// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mpnftmclzdhybbpyeehi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1wbmZ0bWNsemRoeWJicHllZWhpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0Nzc1NDIsImV4cCI6MjA2OTA1MzU0Mn0.Cn0ET1MaMVyMDRAg_FkTegnL5NToo7q_LNBdk65coZ4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});